### PR TITLE
Update SEP_B4_GRIDFIN.cfg

### PR DESCRIPTION
**Pull request by JamesErvin-5**
Temp + title tweaks

### CODE REVIEW

**Comment by SofieBrink** [comment]
May i ask why the Maxtemps of this and the other parts need adjustment?

**Comment by JamesErvin-5** [comment]
It's not even, and the lower temps for the grid fins make them unusable for anything other than landing Superheavy

**Comment by SofieBrink** [comment]
That’s exactly what they are made for though, they are for SuperHeavy. Ofcourse you can use them for other things, but succes isn’t guaranteed.

**Comment by kochiBR** [comment]
> 

so u know KRE grifins exist right ?

**Pull request closed without merging**
