### PR TITLE
The Long Awaited Realism Overhaul Overhaul

### PR DESCRIPTION
**Pull request by Anomalia2022**
PRO

### CODE REVIEW

**Comment by SofieBrink** [comment]
Feels like there was a typo with the raptor namings, i feel like it should be Raptor 1 Boost not Booster

**Comment by Anomalia2022** [comment]
Ah, you are right

**Comment by Anomalia2022** [comment]
Actually, looks like it was always Raptor Booster as the config but Boost makes more sense

**Review by SofieBrink — COMMENTED** [review]
Hopper mass seems off

**Comment by Anomalia2022** [comment]
It isn't actually. The thing was extremely heavy since it was a mass simulator. It also has decent capabilities with the mass I put. Any suggestions on a better mass

**Pull request closed without merging**
