### PR TITLE
Update SEP_RAPTOR_SL.cfg

### PR DESCRIPTION
**Pull request by Fossilized4**
Fix wobbly engines. Idk how this wasn't done sooner.

### CODE REVIEW

**Comment by SofieBrink** [comment]
This is not a fix though… it just makes the issue occur later

**Comment by Fossilized4** [comment]
> This is not a fix though… it just makes the issue occur later

No? I as well as many others use this fix for months and have never re-encountered the issue. Even works on RO

**Comment by SofieBrink** [comment]
It only appeases the incredibly terrible PID's that SAS uses. It does not actually fix the issue fully. Not saying this is a bad PR, just that it doesn't do what it says it does

**Comment by Fossilized4** [comment]
> It only appeases the incredibly terrible PID's that SAS uses. It does not actually fix the issue fully. Not saying this is a bad PR, just that it doesn't do what it says it does

But what's the issue? There are no reported side effects after like ~6+ months

**Comment by SofieBrink** [comment]
The issue is with the SAS PID's

**Pull request closed without merging**
